### ISSUE TITLE
AttributeError: 'str' object has no attribute 'mention'

### ISSUE THREAD

**Issue by joao-0213** [cinderela-baiana/Nerw#15]
Por favor resolva @rodovia

**Comment by rodovia** [comment]
Mas fica a pergunta: quais?

**Comment by joao-0213** [comment]
![Screenshot_20210420-142844_Discord](https://user-images.githubusercontent.com/76481873/115439248-bec30780-a1e4-11eb-9ba8-f0c885ebcf29.jpg)

**Comment by joao-0213** [comment]
Pra falar a vdd acho que é só esse

**Comment by rodovia** [comment]
Ah cara

**Comment by joao-0213** [comment]
Na real nem é um bug

**Comment by joao-0213** [comment]
É só que

**Comment by joao-0213** [comment]
Escreveu Computador maiúsculo

**Comment by joao-0213** [comment]
Só colocar pra transformar tudo em lowercase

**Comment by joao-0213** [comment]
Tlg

**Comment by rodovia** [comment]
Acabei de corrigir o bug, vou fechar o issue🥴
